config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "stories#index"
resources :stories do
resources :characters
end
  get "stories/:id/guess", to: "stories#guess"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :story
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :characters, dependent: :destroy
  accepts_nested_attributes_for :characters, :allow_destroy => true

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController



def new
  @story = Story.find(params[:story_id])
  @character = character.new
end

def create
  @story = Story.find(params[:story_id])
  @character = @story.character.create(character_params)
  redirect_to story_path(@story)
end

def update
  @story = Story.find(params[:story_id])
  @character = Character.find(params[:id])
  @character.update(character_params)
  redirect_to story_path(@story)
end

def edit
  @story = Story.find(params[:story_id])
  @character = Character.find(params[:id])
end

def show
  @character = Character.find(params[:id])
  @story = Story.find(params[:id])

 end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController


def create
  @story = Story.find(params[:id])
  @character = Character.new(params[:character])
    render :action => 'new'
 end

  def edit
      @story = Story.find(params[:id])
    end

def update
      @story = Story.find(params[:id])
     render :action => 'edit'
  end

def show
  @story = Story.find(params[:id])
end

def index
  @stories = Story.all
 end

def guess
  @story = Story.find(params[:id])
end


  def destroy
      @story = Story.find(params[:id])
      @story.destroy
      redirect_to stories_url
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<h1>Here are your characters</h1>
<%= @characters.each do |character| %>
  <div>
    <%= link_to character, characters_path(character) %> - <%= character.story %>
  </div>
<%= end %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>
<h2><%= @character.story.name %></h2>
<div class="character">
  <%= @character.name.id %>
  <%= image_tag @character.img_url %>


<body>

<p>
<button onclick ="@character.img_url()"</button>
</p>

<div id="myContainer">
<div id= "myAnimation">

<script>
  var elem = docmument.getElementById("character.img_url")
  var pos = 0;
  var id = setInterval(frame,10);
  function frame(){
    if(pos == 350){
      clearInterval(id);
    }else{
      pos++;
      elem.style.top = pos + 'px';
      elem.style.left = pos + 'px';
    }
  }
}
</script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThePerry</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stories/index.html.erb
<h1>The Perry Murder Mystery</h1>
<% @stories.each do |story| %>
<div class = "story">
  <h2><%= link_to story.name, story %></h2>
  <p><%= story.description %></p>
  <img src = "<%= story.img_url %>">
</div>
<% end %>

app/views/stories/show.html.erb
<script>
function msg() {
    alert("Correct!")
  }
</script>




<%= @story.name %>
<div class ="character">
  <% @story.characters.each do |character| %>
  <h2><%= character.name %></h2>
  <img src="<%= character.img_url %>">
   <p><%= character.description %></p>
  <% end %>
 </div>

 <!--if killer is correct [then]
 console.log("correct")
 [elsif killer is wrong [then]
 console.log("wrong")] -->



<h3>Guess Who Did it and Who Died</h3>

 <button type="button"
 onclick="document.getElementById('demo').innerHTML = death()">
 Victim</button>
 <textarea name="victim"></textarea>

 <p id="demo"></p>

 <form>
   <input type="button" value="killer" onclick="msg()">
 </form>


 <!-- if killer is correct [then]
  console.log("correct")
 elsif killer is wrong [then]
  console.log("wrong") -->

 <button type="button"
 onclick="document.getElementById('demo').innerHTML = death()">Killer</button>
<textarea name="killer"></textarea>

<p id="demo"></p>

<form>
  <input type="button" value="victim" onclick="msg()">
</form>